#ifndef _POWER_
#define _POWER_

#include "math/EigenWrapper.h"
#include <random>
#include "utils_and_transforms.h"

/**
 * @brief Computes the time derivative of the battery state (SoC and temperature)
 * 
 * @param state : true state vector
 * @param control_input : control input
 * @param u_idx_map : map of control input indices
 * @param G_sp_b : solar panel orientation matrix
 * @param solar_panel_efficiency : efficiency of solar panels
 * @param solar_panel_area : area of each solar panel
 * @param x_idx_map : map of state indices
 * @param battery_capacity : battery capacity in Wh
 * @param battery_thermal_mass : battery thermal mass in J/K
 * @param battery_radiative_loss : battery radiative loss coefficient in W/K^4
 * @param solar_heat_factor : factor converting solar power to heat absorbed by battery
 * @param max_pack_voltage : maximum battery pack voltage in V
 * @param battery_internal_resistance : internal resistance of the battery in Ohms
 * @param mb_power : power consumption of mainboard/base-level power consumption
 * @param num_MTBs : number of magnetorquers
 * @param num_RWs : number of reaction wheels
 * @param jetson_power : Payload power consumption
 * @return time derivative of battery state (SoC and temperature)
 */
VectorXd PowerDynamics(const VectorXd state, const VectorXd control_input, std::unordered_map<std::string, SliceDef> u_idx_map, 
                            MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area, std::unordered_map<std::string, SliceDef> x_idx_map, double battery_capacity, 
                            double battery_thermal_mass, double battery_radiative_loss, double solar_heat_factor, double max_pack_voltage, double battery_internal_resistance,
                            double mb_power, int num_MTBs, int num_RWs, double jetson_power);

/**
 * @brief Returns the power consumption/generation of the spacecraft
 * 
 * @param state : true state vector
 * @param control_input : control input
 * @param u_idx_map : map of control input indices
 * @param G_sp_b : solar panel orientation matrix
 * @param solar_panel_efficiency : efficiency of solar panels
 * @param solar_panel_area : area of each solar panel
 * @param x_idx_map : map of state indices
 * @param mb_power : power consumption of mainboard/base-level power consumption
 * @param num_MTBs : number of magnetorquers
 * @param num_RWs : number of reaction wheels
 * @param jetson_power : Payload power consumption
 * @return power consumption/generation of actuators/solar panels/spacecraft
 */
 VectorXd PowerConsumption(const VectorXd state, const VectorXd control_input, std::unordered_map<std::string, SliceDef> u_idx_map, 
                            MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area, std::unordered_map<std::string, SliceDef> x_idx_map, 
                            double mb_power, int num_MTBs, int num_RWs, double jetson_power);

/**
 * @brief Measures the power consumed by each magnetorquer
 * 
 * @param control_input : Voltages applied to each magnetorquer
 * @param currents : Currents through each magnetorquer
 * @param u_idx_map : map of control input indices
 * @return Power consumption of each magnetorquer
 */
VectorXd MagnetorquerPower(const VectorXd control_input, VectorXd currents, std::unordered_map<std::string, SliceDef> u_idx_map);

/**
 * @brief Measures the solar power generated by each solar panel
 * 
 * @param state : true state vector
 * @param G_sp_b : solar panel orientation matrix
 * @param solar_panel_efficiency : efficiency of solar panels
 * @param solar_panel_area : area of each solar panel
 * @param x_idx_map : map of state indices
 * @return power generation vector for all panels
 */
 VectorXd SolarPanels(const VectorXd state, MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area,
    std::unordered_map<std::string, SliceDef> x_idx_map);

/**
 * @brief Computes the net power draw on the battery
 * 
 * @param state : true state vector
 * @param control_input : control input
 * @param u_idx_map : map of control input indices
 * @param G_sp_b : solar panel orientation matrix
 * @param solar_panel_efficiency : efficiency of solar panels
 * @param solar_panel_area : area of each solar panel
 * @param x_idx_map : map of state indices
 * @param mb_power : power consumption of mainboard/base-level power consumption
 * @param num_MTBs : number of magnetorquers
 * @param num_RWs : number of reaction wheels
 * @param jetson_power : Payload power consumption
 * @return battery diagnostics information
 */
VectorXd Battery(const VectorXd state, const VectorXd control_input, std::unordered_map<std::string, SliceDef> u_idx_map, 
                            MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area, std::unordered_map<std::string, SliceDef> x_idx_map, 
                            double mb_power, int num_MTBs, int num_RWs, double jetson_power);
#endif