#ifndef _POWER_
#define _POWER_

#include "math/EigenWrapper.h"
#include "ParameterParser.h"
#include <random>

/**
 * @brief Returns the power consumption diagnostics
 * 
 * @param state : true state vector
 * @param control_input : control input
 * @param t_J2000 : seconds since J2000 used to read sensors
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return power consumption measurements
 */
result PowerConsumption(const VectorXd state, const VectorXd control_input, Simulation_Parameters sc);

/**
 * @brief Measures the power consumed by each actuator
 * 
 * @param control_input : Voltages applied ot each magnetorquer
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return N_MTB element vector of power consumption
 */
VectorXd MagnetorquerPower(const VectorXd control_input, Simulation_Parameters sc);

/**
 * @brief Measures the solar power generated by each panel
 * 
 * @param state : true state vector
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return power generation vector for all panels
 */
VectorXd SolarPanels(const VectorXd state, Simulation_Parameters sc);

/**
 * @brief Measures the power consumed by each actuator
 * 
 * @param state : true state vector
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return battery diagnostics information
 */
result Battery(const VectorXd state, Simulation_Parameters sc, double net_power_consumption, double solar_heat);

#endif