#ifndef _POWER_
#define _POWER_

#include "math/EigenWrapper.h"
#include <random>
#include "utils_and_transforms.h"


/**
 * @brief Returns the power consumption diagnostics
 * 
 * @param state : true state vector
 * @param control_input : control input
 * @param t_J2000 : seconds since J2000 used to read sensors
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return power consumption measurements
 */
 VectorXd PowerConsumption(const VectorXd state, const VectorXd control_input, VectorXd resistances, std::unordered_map<std::string, SliceDef> u_idx_map, 
                            MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area, std::unordered_map<std::string, SliceDef> x_idx_map, double battery_capacity, 
                            double battery_thermal_mass, double battery_radiative_loss, double solar_heat_factor, double max_pack_voltage, double battery_internal_resistance,
                            double mb_power, int num_MTBs, int num_RWs, double jetson_power);
/**
 * @brief Measures the power consumed by each actuator
 * 
 * @param control_input : Voltages applied ot each magnetorquer
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return N_MTB element vector of power consumption
 */
VectorXd MagnetorquerPower(const VectorXd control_input, VectorXd resistances, std::unordered_map<std::string, SliceDef> u_idx_map);

/**
 * @brief Measures the solar power generated by each panel
 * 
 * @param state : true state vector
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return power generation vector for all panels
 */
 VectorXd SolarPanels(const VectorXd state, MatrixXd G_sp_b, double solar_panel_efficiency, double solar_panel_area,
    std::unordered_map<std::string, SliceDef> x_idx_map);

/**
 * @brief Measures the power consumed by each actuator
 * 
 * @param state : true state vector
 * @param sc : Instance of ParameterParser class holding Sensor noise characterizations
 * @return battery diagnostics information
 */
VectorXd Battery(const VectorXd state, double net_power_consumption, double solar_heat, double battery_capacity,
                double battery_thermal_mass, double battery_radiative_loss, double solar_heat_factor, double max_pack_voltage,
                double battery_internal_resistance, std::unordered_map<std::string, SliceDef> x_idx_map);

#endif